"""Added img_name column

Revision ID: 1aa72356a74b
Revises: 7574d9f69a83
Create Date: 2023-02-19 21:18:24.881025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa72356a74b'
down_revision = '7574d9f69a83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('JKSarees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_name', sa.Text(), nullable=False))
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('JKSarees', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('img_name')

    # ### end Alembic commands ###
