"""back to text

Revision ID: 4c8f2b734534
Revises: 76893b9a3d7e
Create Date: 2023-02-21 09:36:35.569270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c8f2b734534'
down_revision = '76893b9a3d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('JKSarees', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('JKSarees', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
