"""Blob storage

Revision ID: 76893b9a3d7e
Revises: 0482351f9d2e
Create Date: 2023-02-20 21:34:08.397325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76893b9a3d7e'
down_revision = '0482351f9d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('JKSarees', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('JKSarees', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.BLOB(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
